package dev.pillar.osmodule.rsdk

import org.junit.Assert.*
import org.junit.Test

/**
 * Locks the R-SDK encoder to DJI's own output. The three expected frames were generated by compiling
 * the Osmo-GPS-Controller-Demo's CRC + framing code (`custom_crc16.c`, `custom_crc32.c`) with fixed
 * inputs (scratchpad `rsdk_golden.c`) — so a byte-for-byte match proves our framing, both CRCs, the
 * little-endian field packing and the float encoding are all correct.
 */
class RsdkProtocolTest {

    private fun hex(b: ByteArray) = b.joinToString("") { "%02X".format(it) }

    @Test fun connectionRequestMatchesGolden() {
        val mac = byteArrayOf(0x38, 0x34, 0x56, 0x78, 0x9A.toByte(), 0xBC.toByte())
        val payload = RsdkProtocol.connectionRequest(deviceId = 0x12345678, mac = mac, verifyMode = 0, verifyData = 1234)
        val frame = RsdkProtocol.frame(0x00, 0x19, RsdkProtocol.CMD_WAIT_RESULT, payload, seq = 1)
        assertEquals(
            "AA330002000000000100982F00197856341206383456789ABC00000000000000000000000000000000D20400000000A70F381B",
            hex(frame),
        )
    }

    @Test fun gpsPushMatchesGolden() {
        val payload = RsdkProtocol.gpsPush(
            yearMonthDay = 20260718, hourMinuteSecond = 143005,
            longitude1e7 = 21600000, latitude1e7 = 414000000, heightMm = 42000,
            speedNorthCmS = 12.5f, speedEastCmS = -3.25f, speedDownCmS = 0.0f,
            vertAccMm = 1000, horizAccMm = 1000, speedAccCmS = 10, satellites = 11,
        )
        val frame = RsdkProtocol.frame(0x00, 0x17, RsdkProtocol.CMD_NO_RESPONSE, payload, seq = 2)
        assertEquals(
            "AA420000000000000200D34D00176E2735019D2E0200009749018023AD1810A4000000004841000050C000000000E8030000E80300000A0000000B000000FE2937C4",
            hex(frame),
        )
    }

    @Test fun statusSubscriptionMatchesGolden() {
        val payload = RsdkProtocol.statusSubscription(pushMode = 2, pushFreq = 20)
        val frame = RsdkProtocol.frame(0x1D, 0x05, RsdkProtocol.CMD_NO_RESPONSE, payload, seq = 3)
        assertEquals("AA180000000000000300507E1D05021400000000FA4A4931", hex(frame))
    }

    @Test fun parseRoundTripsAndValidatesCrc() {
        val payload = RsdkProtocol.statusSubscription(2, 20)
        val frame = RsdkProtocol.frame(0x1D, 0x05, RsdkProtocol.CMD_NO_RESPONSE, payload, seq = 3)
        val parsed = RsdkProtocol.parse(frame)!!
        assertEquals(0x1D, parsed.cmdSet)
        assertEquals(0x05, parsed.cmdId)
        assertEquals(3, parsed.seq)
        assertFalse(parsed.isResponse)
        assertArrayEquals(payload, parsed.payload)
        // A single flipped byte must fail the CRC check.
        frame[20] = (frame[20] + 1).toByte()
        assertNull(RsdkProtocol.parse(frame))
    }

    @Test fun parsesCameraStatusModeAndRecording() {
        // DJI's packed 38-byte status structure, including values that cross byte boundaries.
        val p = ByteArray(38)
        p[0] = 0x01; p[1] = 0x03; p[2] = 103; p[3] = 3; p[4] = 3
        p[5] = 5; p[8] = 1
        p[11] = 5; p[13] = 60
        p[15] = 0x34; p[16] = 0x12
        p[19] = 100
        p[23] = 0x2C; p[24] = 0x01
        p[27] = 2; p[28] = 0; p[29] = 5; p[30] = 1
        p[31] = 0xE8.toByte(); p[32] = 0x03
        p[35] = 0x2C; p[36] = 0x01; p[37] = 77
        val s = RsdkProtocol.parseCameraStatus(p)!!
        assertEquals("Video", s.modeName)
        assertTrue(s.recording)
        assertEquals(3, s.eisMode)
        assertEquals(0x1234L, s.remainingCapacityMb)
        assertEquals(100L, s.remainingPhotoCount)
        assertEquals(300L, s.remainingRecordTimeS)
        assertEquals(1000L, s.photoCountdownMs)
        assertEquals(300, s.loopRecordSeconds)
        assertEquals(77, s.battery)
    }

    @Test fun allDocumentedCommandPayloadsUseThePackedDjiLayout() {
        assertArrayEquals(ByteArray(0), RsdkProtocol.versionQuery())
        assertEquals("01010000", hex(RsdkProtocol.keyEvent(RsdkProtocol.KeyCode.RECORD)))
        assertEquals("02010200", hex(RsdkProtocol.keyEvent(
            RsdkProtocol.KeyCode.QUICK_SWITCH, RsdkProtocol.KeyEvent.DOUBLE_CLICK,
        )))
        assertEquals("7856341200000000", hex(RsdkProtocol.deviceRestart(0x12345678)))
        assertEquals("785634120A00000000", hex(RsdkProtocol.modeSwitch(
            0x12345678, RsdkProtocol.CameraMode.HYPERLAPSE,
        )))
        assertEquals("03", hex(RsdkProtocol.powerMode(RsdkProtocol.PowerMode.SLEEP)))
    }

    @Test fun wakePayloadContainsPAndTheReversedCameraMac() {
        val mac = byteArrayOf(0x01, 0x02, 0x03, 0x04, 0x05, 0x06)
        assertEquals("50060504030201", hex(RsdkProtocol.wakeManufacturerPayload(mac)))
    }

    @Test fun versionResponseParsesItsFixedAndVariableFields() {
        val product = "DJI-RS3".toByteArray().copyOf(16)
        val tail = "SDK-V1.1\u0000DJI-RS3-001\u000001.00.10.66\u0000".toByteArray()
        val payload = byteArrayOf(0, 0) + product + tail
        val info = RsdkProtocol.parseVersionInfo(payload)!!
        assertEquals(0, info.resultCode)
        assertEquals("DJI-RS3", info.productId)
        assertEquals("SDK-V1.1", info.sdkVersion)
        assertEquals("DJI-RS3-001", info.deviceName)
        assertEquals("01.00.10.66", info.firmwareVersion)
    }

    @Test fun responseCodesUseTheCommandSpecificOffset() {
        fun parsed(set: Int, id: Int, payload: ByteArray) = RsdkProtocol.parse(
            RsdkProtocol.frame(set, id, RsdkProtocol.ACK_WAIT_RESULT, payload, seq = 9),
        )!!

        assertEquals(2, RsdkProtocol.responseCode(parsed(0x1D, 0x03, byteArrayOf(2))))
        assertEquals(1, RsdkProtocol.responseCode(parsed(0x00, 0x16, byteArrayOf(1, 2, 3, 4, 1))))
        assertEquals(0x1234, RsdkProtocol.responseCode(parsed(0x00, 0x00, byteArrayOf(0x34, 0x12))))
    }

    @Test fun shortLegacyStatusKeepsUnknownTailNull() {
        val status = RsdkProtocol.parseCameraStatus(byteArrayOf(5, 3, 4, 1, 0, 0, 0))!!
        assertTrue(status.activeCapture)
        assertFalse("a photo capture is not a recording", status.recording)
        assertNull(status.remainingCapacityMb)
        assertNull(status.battery)
    }
}
